### ISSUE TITLE
Errors with ./auto_convert_ze2_models.sh

### ISSUE THREAD

**Issue by GuyThatExists** [KerJoe/ZeroEscapeRE#1]
After running these scripts a few times, I can't seem to get these scripts to work. Here's the error block that I get for every single model except for the bangle:

![image](https://github.com/user-attachments/assets/bd86f1b5-8e73-488a-a629-07b8011381c2)

I ran everything as-is in the README, with my ze2 directory being < C:\\ze2\\ze2_data_en_us.bin >. The only change I made to any part of the project was changing < /ZeroEscapeRE/.venv/Scripts/ > to < /ZeroEscapeRE/.venv/bin/ > to match what's referenced in the scripts.

No idea what could be going wrong here, as running < ./auto_convert_ze2_models.sh > again after all the .dds files have been created gives the same errors.

**Comment by KerJoe** [comment]
If the .dds files are present, maybe there are problems with backslashes as path separators? Try running in WSL.

**Comment by GuyThatExists** [comment]
running the code in wsl with the code in the other issue worked great. Closing this issue
