### ISSUE TITLE
Errors with ./enable_debug_mode_ze2.sh

### ISSUE THREAD

**Issue by GuyThatExists** [KerJoe/ZeroEscapeRE#2]
I've been running into this problem at the end of running this script, right after allowing a patch to < ze2_data_en_us.bin >. I don't think < workflow/scripts.zip > is ever created in the current version of this project, and that reference is probably what's messing up the code, but I've got no clue how I could fix that on my end. Here's how I'm running the script:

`./enable_debug_mode_ze2.sh C:\\ze2\\ze2-data_en.us.bin C:\\Lua\\5.1\\luac.exe`

And here's what I see after running it:

![image](https://github.com/user-attachments/assets/485db712-d4de-42d1-9b4a-19d66555ce3f)

**Comment by KerJoe** [comment]
As is clearly stated in the output, you don't have the `7z` command. Install 7zip and add it's directory to `PATH`, e.g. `set PATH=%PATH%;"C:\Program Files\7zip"`.

**Comment by KerJoe** [comment]
I have not tested whether the scripts work in Windows, I recommend using the WSL to run them.

**Comment by KerJoe** [comment]
I've updated the `bpy`, so it will run on the current Debian Bookworm in WSL, without installing another version of python.
```
wsl --install Debian

sudo dpkg --add-architecture i386
sudo apt update
sudo apt upgrade
sudo apt install blender python3.11 git unzip p7zip-full python3.11-venv xorg default-jre lua5.1:i386 file

git clone https://github.com/KerJoe/ZeroEscapeRE.git
cd ZeroEscapeRE
python3.11 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
pip install -e `realpath helper`

./extract_ze2_data_en_us.sh /mnt/c/ze2/ze2_data_en.us.bin

./auto_convert_ze2_models.sh

./auto_decompile_lua_scripts.sh
./enable_debug_mode_ze2.sh /mnt/c/ze2/ze2_data_en.us.bin /usr/bin/luac5.1
```

**Comment by GuyThatExists** [comment]
Seems to work great, running the code in wsl let all the models convert correctly. Decompiling and patching the .bin worked great.
